<?php

namespace Handlers\Hooks\Source\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-18 at 15:56:31.
 */
class HookCollectionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HookCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HookCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookCollection::addHook
     * @todo   Implement testAddHook().
     */
    public function testAddHook() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookCollection::addAfterHook
     * @todo   Implement testAddAfterHook().
     */
    public function testAddAfterHook() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookCollection::addBeforeHook
     * @todo   Implement testAddBeforeHook().
     */
    public function testAddBeforeHook() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookCollection::getAfterHooks
     * @todo   Implement testGetAfterHooks().
     */
    public function testGetAfterHooks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookCollection::getBeforeHooks
     * @todo   Implement testGetBeforeHooks().
     */
    public function testGetBeforeHooks() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
