<?php

namespace Handlers\Hooks\Source\Classes;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-18 at 15:56:32.
 */
class HookedClassTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HookedClass
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HookedClass;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookedClass::addMethod
     * @todo   Implement testAddMethod().
     */
    public function testAddMethod() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookedClass::getHookedMethods
     * @todo   Implement testGetHookedMethods().
     */
    public function testGetHookedMethods() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookedClass::getName
     * @todo   Implement testGetName().
     */
    public function testGetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Handlers\Hooks\Source\Classes\HookedClass::setName
     * @todo   Implement testSetName().
     */
    public function testSetName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
